roles:
  - src: geerlingguy.repo-epel   
    version: 1.2.4               

  - src: geerlingguy.repo-remi   
    version: 1.2.0               
    
  - src: geerlingguy.php-versions
    version: 4.0.3
        
  - src: geerlingguy.php
    version: 4.2.0
        
  - src: geerlingguy.composer    
    version: 1.7.6
      
  - src: geerlingguy.mysql
    version: 3.1.0

  - src: geerlingguy.nginx
    version: 2.7.0
