name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: playbook.yml tasks/*.yml
          config_file: .yamllint

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            playbook.yml
            tasks/*.yml

  test:
    name: Molecule
    runs-on: macos-latest
    needs: [yamllint, ansible-lint]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install test dependencies.
        run: pip3 install molecule molecule-vagrant

      - run: |
          cp variables.yml.example variables.yml

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
